### ISSUE TITLE
Installation failed, reverting ./composer.json to its original content

### ISSUE THREAD

**Issue by stoneworld** [ConsoleTVs/Bootpack#11]
laravel5.5.0 
 - consoletvs/bootpack 1.1.0 requires consoletvs/support ^1.0.6 -> satisfiable by consoletvs/support[1.0.6, 1.0.7].
    - consoletvs/bootpack 1.1.1 requires consoletvs/support ^2.2.0 -> satisfiable by consoletvs/support[2.2.0, 2.2.1, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.5].
    - consoletvs/bootpack 1.1.2 requires consoletvs/support ^2.2.0 -> satisfiable by consoletvs/support[2.2.0, 2.2.1, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.5].
    - consoletvs/bootpack 1.1.3 requires consoletvs/support ^2.2.0 -> satisfiable by consoletvs/support[2.2.0, 2.2.1, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.5].
    - consoletvs/bootpack 1.1.4 requires consoletvs/support ^2.2.0 -> satisfiable by consoletvs/support[2.2.0, 2.2.1, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.5].
    - consoletvs/bootpack 1.1.5 requires consoletvs/support ^2.2.0 -> satisfiable by consoletvs/support[2.2.0, 2.2.1, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.5].
    - consoletvs/bootpack 1.1.6 requires consoletvs/support ^2.2.0 -> satisfiable by consoletvs/support[2.2.0, 2.2.1, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.5].
    - consoletvs/bootpack 1.1.7 requires consoletvs/support ^2.2.0 -> satisfiable by consoletvs/support[2.2.0, 2.2.1, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.5].
    - consoletvs/bootpack 1.1.8 requires consoletvs/support ^2.2.0 -> satisfiable by consoletvs/support[2.2.0, 2.2.1, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.5].
    - consoletvs/support 1.0.6 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1].
    - consoletvs/support 1.0.7 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1].
    - consoletvs/support 2.2.0 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1].
    - consoletvs/support 2.2.1 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1].

**Comment by ConsoleTVs** [comment]
PHP version?
intervention/image version?
