### ISSUE TITLE
Error Exception, Undefined offset: 1

### ISSUE THREAD

**Issue by espositodaniele** [ConsoleTVs/Bootpack#4]
Hello, 

have followed the instruction to install the package as written in the documentation, at the final step I got this error: 
  [ErrorException]
  Undefined offset: 1.

Any suggestion on how can I resolve that? 

![bootpack](https://user-images.githubusercontent.com/26567236/31765198-eef487b0-b4c3-11e7-8a9b-b9148be9bfbe.PNG)

Here is a screenshot of the error. 

Thanks

D

**Comment by ConsoleTVs** [comment]
Do u have permissions for it? I'll keep an eye into it

**Comment by espositodaniele** [comment]
Yes, I did with Administrator permission, but nothing either.

**Comment by espositodaniele** [comment]
I have checked the error in the log file and I got this: 
local.ERROR: Undefined offset: 1 {"exception":"[object] (ErrorException(code: 0): Undefined offset: 1 at ....\\vendor\\consoletvs\\bootpack\\src\\Classes\\Package.php:50

It might be helpful.

D

**Comment by ConsoleTVs** [comment]
Traceback: https://github.com/ConsoleTVs/Bootpack/blob/master/src/Commands/BootpackCreatePackage.php#L76

https://github.com/ConsoleTVs/Bootpack/blob/master/src/Classes/Package.php#L50

The explode should always return an array of 2 items offsets: 0, 1. As you can see, the explode explodes the name of the package as:

test/package => 0 - test, 1 - package, offset 1 should be "package" in my example. Have you tried using the default name in the package description?

```
php artisan bootpack:create test/package
```

**Comment by espositodaniele** [comment]
Everything works fine when I install with test/package name as you said, but why? Shall I always use {name}/package as name and namespace? 

Thanks 

D

**Comment by ConsoleTVs** [comment]
Try using {name}/{package} without spaces, dadhes, slashes or capital letters
