### ISSUE TITLE
Comma in config/app.php is missing

### ISSUE THREAD

**Issue by lukacavic** [ConsoleTVs/Bootpack#7]
Package is great, but one small error. When generating service provider, comma is not added on end and app has compailer errors.

Thats all, everything else good :)

**Comment by ConsoleTVs** [comment]
Can u tell me where please?

**Comment by ConsoleTVs** [comment]
https://github.com/ConsoleTVs/Bootpack/releases/tag/1.1.8

This fixed the issue, thanks!
